### ISSUE TITLE
Access Denied Error when Running `get_dataset.py`

### ISSUE THREAD

**Issue by dohyun1411** [1989Ryan/paragon#2]
When running `python3 get_dataset.py`, I encountered the following error message:
```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?export=download&id=1WxfGi-CfmvQODyQgTkrAfCSQHPmNRMsE
```
I have also tried accessing the link directly, but the download always fails.

Please assist me in resolving this issue.

**Comment by 1989Ryan** [comment]
It is due to the problem of gdown: https://github.com/wkentaro/gdown/issues/43. Please update gdown in your docker container.

**Comment by dohyun1411** [comment]
> It is due to the problem of gdown: [wkentaro/gdown#43](https://github.com/wkentaro/gdown/issues/43). Please update gdown in your docker container.

I have updated gdown to the latest version (4.6.2), but I am still encountering the same error.
Here is the result of running pip show down:
```
Name: gdown
Version: 4.6.2
Summary: Google Drive direct download of big files.
Home-page: http://github.com/wkentaro/gdown
Author: Kentaro Wada
Author-email: www.kentaro.wada@gmail.com
License: MIT
Location: /home/user/.local/lib/python3.6/site-packages
Requires: beautifulsoup4, filelock, requests, six, tqdm
Required-by:
```

**Comment by 1989Ryan** [comment]
I have tried, and it is okay. It is due to too many visiting times. Could you try to download it later? Have you downloaded the dataset?

**Comment by dohyun1411** [comment]
Yes, I downloaded the test dataset first, and now I am trying to download the train dataset

**Comment by 1989Ryan** [comment]
I have made some revisions. please pull the repo before you download the pre-trained models.

**Comment by dohyun1411** [comment]
I've been experiencing difficulty in downloading the train data. I've tried using different devices and networks, but the download still fails.
I noticed that the test data link works well, so I suspect that the size of the train data may be causing the issue.
Could you provide me with an alternative way to download the train data?

**Comment by 1989Ryan** [comment]
I'm sorry I cannot find an alternative way because of the dataset size. You can download it on google drive in a browser.
